### ISSUE TITLE
Hours charts not displaying for year 2020

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/StaffPlan#158]
Looks like it's happening for the entire team.
https://www.staffplan.com/staffplans

Looking at my staff plan, there are hours planned for next year but it's not visible in the chart at the top.
https://www.staffplan.com/staffplans/4

Noticing in Safari 12.1, Mac 10.14.4

**Comment by craigmcginley** [comment]
Works for me, Safari and Chrome. Maybe try updating Safari?
<img width="1438" alt="Screen Shot 2019-11-04 at 4 54 07 PM" src="https://user-images.githubusercontent.com/6530818/68161394-d12f7f80-ff23-11e9-9503-2495975a9d15.png">

**Comment by ericbenwa** [comment]
Nevermind!
Had my fiscal year toggle onto 2019 only.
